//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        public int ID { get; set; }
        public int ParentBranch { get; set; }
        public string EmergencyAmbulance { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
