//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erschedulerEntities1 : DbContext
    {
        public erschedulerEntities1()
            : base("name=erschedulerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<PlaceOfLiving> PlaceOfLiving { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Work_Data> Work_Data { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
