//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int OIB { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public int Gender { get; set; }
        public string Address { get; set; }
        public int Hometown { get; set; }
        public int Home_Telephone { get; set; }
        public int Mobile_Phone { get; set; }
        public string Note { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual PlaceOfLiving PlaceOfLiving { get; set; }
        public virtual Work_Data Work_Data { get; set; }
    }
}
